### ISSUE TITLE
No uptime on openSUSE.

### ISSUE THREAD

**Issue by ToboSK** [jornmann/zfetch#7]
![image](https://user-images.githubusercontent.com/82178536/157239841-b9ec8369-c22b-4c8b-91a0-529f13159da1.png)

**Comment by jornmann** [comment]
We could attempt to get the uptime from /proc/uptime, where it is stored in seconds. We'd need a way to convert this to minutes, hours, and days, and weeks, though.
@ToboSK, does openSUSE have /proc/uptime?

**Comment by ToboSK** [comment]
> 

Yeah, the values are "879.38 1534.51"
Neofetch shows uptime 16 minutes.

**Comment by Damaj301damaj-lol** [comment]
> We could attempt to get the uptime from /proc/uptime, where it is stored in seconds. We'd need a way to convert this to minutes, hours, and days, and weeks, though.
> @ToboSK, does openSUSE have /proc/uptime?

I suggests that we do this only on specific distros, android for example doesn't allow reading from /proc/uptime but its definitely there
